#!/bin/bash

SHIPS=( Carrier Battleship Submarine Destroyer Dingy )
LENGTHS=( 5 4 3 3 2 )
COUNT=${#SHIPS[@]}

function increment_char {
    times=$2
    char=$1
    i=0
    while [[ $i -lt $times ]]; do
	char=`echo $char | tr 'A-L' 'B-M'`
	i=$((i+1))
    done
    echo $char
}

function increment_num {
    times=$2
    num=$1
    i=0
    while [[ $i -lt $times ]]; do
	num=$((num+1))
    done
    echo $num
}

function query_for_ship {
    unset ship
    until index_of $ship; 
    do
	echo Which ship would you like to place?
	for s in ${SHIPS[@]}
	do
	    echo $s
	done
	echo -----------------------------------
	read ship
	clear

	if ! index_of $ship
	then
	    echo "$ship is not a ship you can place"
	fi
	ship=$ship
    done
}

function init_board {
    rm -rf .state
    for i in {A..Z}
    do
	mkdir -p .state/$i
    done
}

function index_of { # ship
    i=0
    local_ship=$1
    if [ -z $local_ship ]
    then
	return `false`
    fi
    while [ $i -lt $COUNT ]
    do
	s=${SHIPS[$i]}
	if [ -n $s ]; then
	    if [ $local_ship == "$s" ]
	    then
		index=$i
		return `true`
	    fi
	fi
	i=`expr $i + 1`
    done
    return `false`
}

function increment_char {
    times=$2
    char=$1
    i=0
    while [[ $i -lt $times ]]; do
	char=`echo $char | tr 'A-L' 'B-M'`
	i=$((i+1))
    done
    echo $char
}

function increment_num {
    times=$2
    num=$1
    i=0
    while [[ $i -lt $times ]]; do
	num=$((num+1))
	i=$((i+1))
    done
    echo $num
}

function place_ship_vertically {
    local_ship=$1
    local_row=$2
    local_col=$3
    index_of $local_ship
    length=${LENGTHS[$index]}
    i=0
    unset locations
    while [ $i -lt $length ]
    do
	mutable_row=`increment_num $local_row $i`
	locations="$locations $3$mutable_row"
	i=`expr $i + 1`
    done
    
    if ./check_locations $locations
    then
	./place_locations $locations
    else
	echo "This position will hit another ship or go off board"
	return `false`
    fi
    return `true`
}

function place_ship_horizontally {
    local_ship=$1
    local_row=$2
    local_col=$3
    index_of $local_ship
    length=${LENGTHS[$index]}
    i=0
    unset locations
    while [ $i -lt $length ]
    do
	mutable_col=`increment_char $local_col $i`
	locations="$locations $mutable_col$2"
	i=`expr $i + 1`
    done
    
    
    if ./check_locations $locations
    then
	./place_locations $locations
    else
	echo "This position will hit another ship or go off board"
	return `false`
    fi
    return `true`
}


function place_ship {
    SHIP=$1
    ROW=$2
    COL=$3
    DIRECTION=$4
    echo Placing $SHIP at $COL $ROW facing $DIRECTION
    if index_of $SHIP
    then
	index_of $SHIP
	if [ $DIRECTION = Vertical ]
	then
	    if place_ship_vertically $1 $2 $3; then
		unset SHIPS[$index]
	    fi
	else
	    if place_ship_horizontally $1 $2 $3; then
		unset SHIPS[$index]
	    fi
	fi
    else
	echo "Ship not found"
    fi
}

function place_ships {
    until [[ ${#SHIPS[@]} == '0' ]]; do
	query_for_ship
	echo Where would you like to place your $ship?
	read starting_point
	clear
	echo Which direction would you like it to face?
	echo Horizontal
	echo Vertical
	echo ------------------------------------------
	read direction
	clear
	row=`echo $starting_point | sed 's:[A-Z ]::g'`
	col=`echo $starting_point | sed 's:[0-9 ]::g'`
	place_ship $ship $row $col $direction
	./print_board
	unset $ship
    done
}
# --- MAIN ---
clear
echo Initializing board
init_board
place_ships

