#!/bin/bash

function handle-command {
    command=$1
    row=$2
    col=$3
    case $command in
	"target" )
	    if ./$command $row $col
	    then
		echo HIT
	    else
		echo MISS
	    fi
	    ;;
    esac
    echo $result > result
}

read command_input
args=`echo $command_input | sed "s: ::g" | sed "s:[{}]: :g" | sed "s:\([A-Z]\):\1 :g"`
handle-command $args